import "pkg:/source/KeyEventAdapter.bs"

sub init()
    ' m.top.setFocus(true)
    go = m.top.findNode("go")
    go.setFocus(true)
end sub

function onKeyEvent(key as string, press as boolean) as boolean
    ? m.top.subtype() "/" m.top.id ".onKeyEvent received: " key " " press 
    retval = key = "back" ? true : false 'prevent app exit via back key
    ? m.top.subtype() "/" m.top.id " returns " retval 
    return retval
end function